### ISSUE TITLE
Google Analytics is not working in post pages

### ISSUE THREAD

**Issue by monkeyWzr** [monkeyWzr/hugo-theme-cactus#34]
It seems that ga script is not loaded

**Comment by monkeyWzr** [comment]
false negative

**Comment by 216049245** [comment]
Hi there is there anything else I need to do to get Google analytics to work besides adding in the measurement ID on the config.toml file?

**Comment by andodet** [comment]
@monkeyWzr It seems somethig might be up with Google Analytics as setting the tracking id as `googleAnalytics` in the `config.toml` file is not enough to get the script into the header section.

**Comment by monkeyWzr** [comment]
@216049245 @andodet 
Sorry for the delay. I can’t remember why I closed this one as a false negative issue. I’ll handle this asap

**Comment by andodet** [comment]
@monkeyWzr thanks for the very quick reply, let me know if I can assist troubleshooting in any way.

**Comment by monkeyWzr** [comment]
@andodet Hi there
I'll appreciate it if you can share some information:
* what is the ga version you are using, V3 (id looks like UA-XXXXXXXX-X), or V4 (id looks like G-XXXXXXXX)
* do you have your googleAnalytics set at the right place, like this: 

```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cactus"
googleAnalytics = "G-XXXXXXXX" # this one must be set at top level instead of under [params]
# ...

[params]
# ...
```
