### ISSUE TITLE
Logo greyed out until hovered over

### ISSUE THREAD

**Issue by bool3max** [monkeyWzr/hugo-theme-cactus#65]
I've set a custom homepage logo (by creating `/static/images/logo.png`), however it is completely greyed out until it is hovered over:

![20210701_11h57m20s_grim](https://user-images.githubusercontent.com/12991998/124105610-ab91ab00-da63-11eb-8960-cf4f7814f80c.png)

After I hover over it:

![20210701_11h58m11s_grim](https://user-images.githubusercontent.com/12991998/124105643-b8160380-da63-11eb-90a1-fbd85cbf394e.png)

---

Is there any way to disable this behavior and have the logo be fully colored at all times?

**Comment by bool3max** [comment]
I managed to solve the issue by commenting out the following styles in the CSS files of the desired theme:

```css
#header #logo {
    filter: grayscale(100%);
    -webkit-filter: grayscale(100%);
}
```

Still, it would be good if this option was configurable.
